(module
 (rec
  (type $0 (sub (array (mut f32))))
  (type $1 (array (mut v128)))
  (type $2 (descriptor $4) (struct (field f64) (field (ref $5))))
  (type $3 (array i32))
  (type $4 (describes $2) (descriptor $5) (struct (field (mut v128)) (field (mut (ref $12)))))
  (type $5 (sub (describes $4) (struct)))
  (type $6 (array (ref any)))
  (type $7 (sub (struct (field (mut i16)) (field f32) (field (mut f64)) (field (mut (ref null $12))) (field (mut (ref $11))))))
  (type $8 (struct (field (mut f64)) (field i8) (field (mut i8)) (field (mut v128)) (field (mut (ref null $8)))))
  (type $9 (sub (array (mut i8))))
  (type $10 (sub (array (mut i16))))
  (type $11 (struct (field (mut i16)) (field (ref struct)) (field f32) (field (mut nullexternref)) (field (ref struct))))
  (type $12 (array (mut i32)))
  (type $13 (sub (struct (field i64))))
 )
 (rec
  (type $14 (sub (func (result (ref null $11)))))
  (type $15 (func))
  (type $16 (func (param v128)))
  (type $17 (func (param (ref null $8))))
  (type $18 (array i8))
  (type $19 (struct (field i64) (field i32) (field i8) (field (mut v128)) (field (mut (ref null $13)))))
  (type $20 (struct))
 )
 (type $21 (func (param i32)))
 (type $22 (func (param externref)))
 (type $23 (func (param (ref null $8))))
 (type $24 (func (param v128)))
 (type $25 (func))
 (import "__fuzz_import" "global$_9" (global $gimport$0 externref))
 (import "__fuzz_import" "extern$" (global $gimport$1 (ref extern)))
 (import "fuzzing-support" "wasmtag" (tag $eimport$0 (type $21) (param i32)))
 (import "fuzzing-support" "jstag" (tag $eimport$1 (type $22) (param externref)))
 (global $global$0 (ref $7) (struct.new $7
  (i32.const 0)
  (f32.const 0)
  (f64.const 0)
  (ref.null none)
  (struct.new $11
   (i32.const 0)
   (struct.new_default $20)
   (f32.const 0)
   (ref.null noextern)
   (struct.new_default $20)
  )
 ))
 (global $global$1 (mut f64) (f64.const 0))
 (global $global$2 i32 (i32.const 0))
 (global $global$3 externref (ref.null noextern))
 (global $global$4 i32 (i32.const 0))
 (global $global$5 i32 (i32.const 0))
 (global $global$6 f32 (f32.const 0))
 (global $global$7 i64 (i64.const 0))
 (global $global$8 (ref struct) (struct.new_default $20))
 (global $global$9 (ref eq) (struct.new_default $20))
 (global $global$10 f64 (f64.const 0))
 (global $global$11 (ref null $19) (struct.new_default $19))
 (global $global$12 (ref $11) (struct.new $11
  (i32.const 0)
  (struct.new_default $20)
  (f32.const 0)
  (ref.null noextern)
  (global.get $global$8)
 ))
 (global $global$13 (ref array) (array.new_fixed $18 0))
 (global $global$14 funcref (ref.null nofunc))
 (global $global$15 i64 (i64.const 0))
 (global $global$16 i64 (i64.const 0))
 (global $global$17 i64 (i64.const 0))
 (global $global$18 (mut i32) (i32.const 0))
 (global $global$19 i32 (i32.const 0))
 (memory $0 i64 16 17 shared)
 (table $0 7 7 funcref)
 (table $1 2 exnref)
 (elem $0 (table $0) (i32.const 0) func)
 (tag $tag$0 (type $23) (param (ref null $8)))
 (tag $tag$1 (type $24) (param v128))
 (tag $tag$2 (type $25))
 (export "global$_7" (global $global$12))
 (func $0 (type $14) (result (ref null $11))
  (try
   (do
    (unreachable)
   )
   (catch $tag$0
    (drop
     (struct.get $8 0
      (pop (ref null $8))
     )
    )
    (unreachable)
   )
   (catch_all
    (unreachable)
   )
  )
  (unreachable)
 )
)
