;; Allocates and inspects objects of the generator's types from JS.  The rec
;; groups are identical to gen_gc.py's, so V8 canonicalises them to the same
;; types as the module under test.
(module
  (type $S0 (struct (field (mut i32)) (field (mut i8)) (field i16) (field (mut i64))))
  (type $S1 (struct (field i32) (field (mut (ref null $S0))) (field (mut i32))))
  (type $S2 (struct (field (mut i32))))
  (type $A0 (array (mut i32)))
  (type $A1 (array (mut i8)))
  (type $A2 (array i16))
  (type $A3 (array (mut (ref null $S2))))
  (func (export "new_S0") (param i32 i32 i32 i64) (result (ref $S0))
    (struct.new $S0 (local.get 0) (local.get 1) (local.get 2) (local.get 3)))
  (func (export "new_S1") (param i32 i32) (result (ref $S1))
    (struct.new $S1 (local.get 0) (ref.null $S0) (local.get 1)))
  (func (export "new_S2") (param i32) (result (ref $S2))
    (struct.new $S2 (local.get 0)))
  (func (export "new_A0") (param i32 i32) (result (ref $A0))
    (array.new_fixed $A0 2 (local.get 0) (local.get 1)))
  (func (export "new_A1") (param i32 i32) (result (ref $A1))
    (array.new_fixed $A1 2 (local.get 0) (local.get 1)))
  (func (export "new_A2") (param i32 i32) (result (ref $A2))
    (array.new_fixed $A2 2 (local.get 0) (local.get 1)))
  (func (export "new_A3") (result (ref $A3))
    (array.new_default $A3 (i32.const 2)))
  (func (export "S0_0") (param (ref $S0)) (result i32) (struct.get $S0 0 (local.get 0)))
  (func (export "S0_1") (param (ref $S0)) (result i32) (struct.get_u $S0 1 (local.get 0)))
  (func (export "S0_2") (param (ref $S0)) (result i32) (struct.get_u $S0 2 (local.get 0)))
  (func (export "S0_3") (param (ref $S0)) (result i64) (struct.get $S0 3 (local.get 0)))
  (func (export "S1_0") (param (ref $S1)) (result i32) (struct.get $S1 0 (local.get 0)))
  (func (export "S1_1") (param (ref $S1)) (result (ref null $S0)) (struct.get $S1 1 (local.get 0)))
  (func (export "S1_2") (param (ref $S1)) (result i32) (struct.get $S1 2 (local.get 0)))
  (func (export "S2_0") (param (ref $S2)) (result i32) (struct.get $S2 0 (local.get 0)))
  (func (export "A0_len") (param (ref $A0)) (result i32) (array.len (local.get 0)))
  (func (export "A1_len") (param (ref $A1)) (result i32) (array.len (local.get 0)))
  (func (export "A2_len") (param (ref $A2)) (result i32) (array.len (local.get 0)))
  (func (export "A3_len") (param (ref $A3)) (result i32) (array.len (local.get 0)))
  (func (export "A0_get") (param (ref $A0) i32) (result i32) (array.get $A0 (local.get 0) (local.get 1)))
  (func (export "A1_get") (param (ref $A1) i32) (result i32) (array.get_u $A1 (local.get 0) (local.get 1)))
  (func (export "A2_get") (param (ref $A2) i32) (result i32) (array.get_u $A2 (local.get 0) (local.get 1)))
  (func (export "A3_get") (param (ref $A3) i32) (result (ref null $S2)) (array.get $A3 (local.get 0) (local.get 1)))
)
